---

- name: Criação de usuários Redes Admin na Oracle Cloud Infrastructure
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    parent_compartment_ocid: "{{ lookup('env', 'PARENT_COMPARTMENT_OCID') }}"
    group_name: "RedesAdmin"
    dominio: "@email.com"
    usuarios:
      - user9
      - user10

  tasks:
   - name: Valida pre-requisitos
     fail:
       msg: "Variavel de ambiente {{item}} nao definida. Por favor corrigir."
     when: item not in ansible_env
     with_items:
       - "PARENT_COMPARTMENT_OCID"
    
   - name: Obtém ID do Grupo
     oci_identity_group_facts:
       name: "{{ group_name }}"
       compartment_id: "{{ parent_compartment_ocid }}"
     register: result 
   - set_fact: 
       group_ocid: "{{ result.groups[0].id }}"
  
   - name: Cria usuários, adiciona em grupo e define senha
     include_tasks: "iam-cria-usuarios.yaml"
     loop: "{{ usuarios }}"
